name: nepal_np
description: "Nepal Heritage — discover temples, festivals, hidden gems and local guides."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-300normal.ttf
          weight: 300
        - asset: assets/fonts/DMSans-400normal.ttf
          weight: 400
        - asset: assets/fonts/DMSans-500normal.ttf
          weight: 500
        - asset: assets/fonts/DMSans-600normal.ttf
          weight: 600
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-400normal.ttf
          weight: 400
        - asset: assets/fonts/Lora-400italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lora-600normal.ttf
          weight: 600
        - asset: assets/fonts/Lora-600italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Lora-700normal.ttf
          weight: 700
